"""Add rejection_reason fields to blogs and resources

Revision ID: 73951d288991
Revises: dfb8e3ba9630
Create Date: 2025-09-15 00:03:10.619160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73951d288991'
down_revision = 'dfb8e3ba9630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')

    # ### end Alembic commands ###
