"""Add invitations table and invited_by_user_id to users

Revision ID: 9408c371ccc5
Revises: cc2f312f1ccb
Create Date: 2025-09-05 02:36:46.387036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9408c371ccc5'
down_revision = 'cc2f312f1ccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('inviter_user_id', sa.UUID(), nullable=False),
    sa.Column('invitee_email', sa.Text(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitations_invitee_email'), ['invitee_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_token'), ['token'], unique=True)

    # Update existing posts with NULL display_name to have a default value
    op.execute("UPDATE posts SET display_name = 'Anonymous' WHERE display_name IS NULL")

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('display_name',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invited_by_user_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['invited_by_user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('invited_by_user_id')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('display_name',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_token'))
        batch_op.drop_index(batch_op.f('ix_invitations_invitee_email'))

    op.drop_table('invitations')
    # ### end Alembic commands ###
