"""Add NCLEX course tables

Revision ID: a1b2c3d4e5f6
Revises: e73b83063d18
Create Date: 2025-11-09 10:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'e73b83063d18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nclex_courses',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.CHAR(length=36), nullable=True),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nclex_enrollments',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('course_id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('latest_score_percent', sa.Float(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['nclex_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'user_id', name='uq_course_user_enrollment')
    )
    op.create_table('nclex_course_resources',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('course_id', sa.CHAR(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('storage_filename', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['nclex_courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nclex_questions',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('course_id', sa.CHAR(length=36), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['nclex_courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nclex_attempts',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('enrollment_id', sa.CHAR(length=36), nullable=False),
    sa.Column('score_percent', sa.Float(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['nclex_enrollments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nclex_question_options',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('question_id', sa.CHAR(length=36), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['nclex_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nclex_attempt_answers',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('attempt_id', sa.CHAR(length=36), nullable=False),
    sa.Column('question_id', sa.CHAR(length=36), nullable=False),
    sa.Column('selected_option_id', sa.CHAR(length=36), nullable=True),
    sa.Column('correct_option_id', sa.CHAR(length=36), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['nclex_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['correct_option_id'], ['nclex_question_options.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['nclex_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['nclex_question_options.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nclex_course_resources_course_order', 'nclex_course_resources', ['course_id', 'order_index'])
    op.create_index('ix_nclex_questions_course_order', 'nclex_questions', ['course_id', 'order_index'])
    op.create_index('ix_nclex_attempts_enrollment', 'nclex_attempts', ['enrollment_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nclex_attempts_enrollment', table_name='nclex_attempts')
    op.drop_index('ix_nclex_questions_course_order', table_name='nclex_questions')
    op.drop_index('ix_nclex_course_resources_course_order', table_name='nclex_course_resources')
    op.drop_table('nclex_attempt_answers')
    op.drop_table('nclex_question_options')
    op.drop_table('nclex_attempts')
    op.drop_table('nclex_questions')
    op.drop_table('nclex_course_resources')
    op.drop_table('nclex_enrollments')
    op.drop_table('nclex_courses')
    # ### end Alembic commands ###


