"""Add department and bio fields to User

Revision ID: cc2f312f1ccb
Revises: db89c42dd8e4
Create Date: 2025-09-05 02:25:20.682368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc2f312f1ccb'
down_revision = 'db89c42dd8e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('display_name',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('department')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('display_name',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
