"""Add title, state to User and display_name to Post

Revision ID: db89c42dd8e4
Revises: 8b2e5688b73a
Create Date: 2025-09-04 19:22:57.899001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db89c42dd8e4'
down_revision = '8b2e5688b73a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('title')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
