"""Add image_url and is_visible fields to broadcast_messages

Revision ID: dfb8e3ba9630
Revises: e4559d316191
Create Date: 2025-09-14 23:03:38.021674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb8e3ba9630'
down_revision = 'e4559d316191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broadcast_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broadcast_messages', schema=None) as batch_op:
        batch_op.drop_column('is_visible')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
