"""Add tags array field to Post model

Revision ID: dfd6e33eec5e
Revises: 9408c371ccc5
Create Date: 2025-09-06 20:14:20.169271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dfd6e33eec5e'
down_revision = '9408c371ccc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
